services:
  backend_green:
    image: nginx:alpine
    volumes:
      - ./message.txt:/usr/share/nginx/html/index.html:ro
    expose:
      - "80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost"]
      interval: 2s
      timeout: 1s
      retries: 10

  backend_blue:
    image: nginx:alpine
    volumes:
      - ./message.txt:/usr/share/nginx/html/index.html:ro
    expose:
      - "80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost"]
      interval: 2s
      timeout: 1s
      retries: 10
